*&---------------------------------------------------------------------*
*&  Include           /VPCOE/MAT_DOC_TO_RDP_SCR_NRML
*&---------------------------------------------------------------------*
INCLUDE /vpcoe/version.
INCLUDE /vpcoe/i_delta_ss.

SELECTION-SCREEN BEGIN OF BLOCK options WITH FRAME TITLE text-004.
PARAMETERS: p_cselid TYPE /vpcoe/de_sel_name.
PARAMETERS: r_screen RADIOBUTTON GROUP req USER-COMMAND et.

PARAMETERS: r_send  RADIOBUTTON GROUP req.
SELECTION-SCREEN BEGIN OF BLOCK send_opt.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 4(30) text-psm FOR FIELD p_mtrl MODIF ID sop.
SELECTION-SCREEN POSITION 3.
PARAMETERS: p_mtrl  TYPE xfeld AS CHECKBOX DEFAULT 'X' USER-COMMAND mtrl MODIF ID sop.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 4(30) text-psb FOR FIELD p_bilds MODIF ID sop.
SELECTION-SCREEN POSITION 3.
PARAMETERS: p_bilds TYPE xfeld AS CHECKBOX USER-COMMAND blds MODIF ID sop.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 4(30) text-psi FOR FIELD p_supis MODIF ID sop.
SELECTION-SCREEN POSITION 3.
PARAMETERS: p_supis TYPE xfeld AS CHECKBOX USER-COMMAND supl MODIF ID sop.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK send_opt.

PARAMETERS: r_excel RADIOBUTTON GROUP req.
INCLUDE /vpcoe/i_excel_selscr.
SELECTION-SCREEN END OF BLOCK options.

INCLUDE /vpcoe/billdi.

INCLUDE /vpcoe/supinvi.

SELECTION-SCREEN BEGIN OF BLOCK seldata WITH FRAME TITLE text-002.
SELECT-OPTIONS:
  so_cntry FOR t001w-land1 NO INTERVALS OBLIGATORY,     "Country
  so_post  FOR mseg-budat_mkpf, "Posting Date
  so_year  FOR mseg-mjahr,       "Material Document Year
  so_werks FOR mseg-werks,
  so_mdoc  FOR mseg-mblnr,
  so_type  FOR mseg-bwart,
  so_matnr FOR mseg-matnr,
  so_mtart FOR mara-mtart,
  so_vkorg FOR mvke-vkorg.
SELECTION-SCREEN END OF BLOCK seldata.

ENHANCEMENT-POINT /vpcoe/mat_doc_bck_sel_scr SPOTS /vpcoe/enh_mat_dock_bck .

SELECTION-SCREEN BEGIN OF BLOCK variants WITH FRAME TITLE text-003.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_gr_pr  TYPE xfeld  AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN COMMENT (70) text-006 FOR FIELD p_gr_pr.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_gi_pr  TYPE xfeld AS CHECKBOX DEFAULT '' MODIF ID off.
SELECTION-SCREEN COMMENT (70) text-007 FOR FIELD p_gi_pr MODIF ID off.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_gr_st  TYPE xfeld AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN COMMENT (77) text-008 FOR FIELD p_gr_st.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_gr_std  TYPE xfeld AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN COMMENT (77) text-014 FOR FIELD p_gr_std.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_gi_st  TYPE xfeld AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN COMMENT (77) text-009 FOR FIELD p_gi_st.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_gi_std  TYPE xfeld AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN COMMENT (77) text-015 FOR FIELD p_gi_std.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_gr_poi TYPE xfeld AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN COMMENT (77) text-010 FOR FIELD p_gr_poi.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_gr_po  TYPE xfeld AS CHECKBOX DEFAULT 'X'.
SELECTION-SCREEN COMMENT (77) text-011 FOR FIELD p_gr_po.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_gi_soe TYPE xfeld AS CHECKBOX DEFAULT '' MODIF ID off.
SELECTION-SCREEN COMMENT (70) text-012 FOR FIELD p_gi_soe MODIF ID off.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS: p_gi_so  TYPE xfeld AS CHECKBOX MODIF ID off.
SELECTION-SCREEN COMMENT (70) text-013 FOR FIELD p_gi_so MODIF ID off.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK variants.
