*---------------------------------------------------------------------*
*    view related data declarations
*---------------------------------------------------------------------*
*...processing: /VPCOE/CONF_PARM................................*
DATA:  BEGIN OF STATUS_/VPCOE/CONF_PARM              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_/VPCOE/CONF_PARM              .
CONTROLS: TCTRL_/VPCOE/CONF_PARM
            TYPE TABLEVIEW USING SCREEN '0800'.
*...processing: /VPCOE/RDPSMSRVV................................*
TABLES: /VPCOE/RDPSMSRVV, */VPCOE/RDPSMSRVV. "view work areas
CONTROLS: TCTRL_/VPCOE/RDPSMSRVV
TYPE TABLEVIEW USING SCREEN '0104'.
DATA: BEGIN OF STATUS_/VPCOE/RDPSMSRVV. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/VPCOE/RDPSMSRVV.
* Table for entries selected to show on screen
DATA: BEGIN OF /VPCOE/RDPSMSRVV_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /VPCOE/RDPSMSRVV.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /VPCOE/RDPSMSRVV_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /VPCOE/RDPSMSRVV_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /VPCOE/RDPSMSRVV.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /VPCOE/RDPSMSRVV_TOTAL.

*...processing: /VPCOE/RDPVSRVGR................................*
TABLES: /VPCOE/RDPVSRVGR, */VPCOE/RDPVSRVGR. "view work areas
CONTROLS: TCTRL_/VPCOE/RDPVSRVGR
TYPE TABLEVIEW USING SCREEN '0401'.
DATA: BEGIN OF STATUS_/VPCOE/RDPVSRVGR. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/VPCOE/RDPVSRVGR.
* Table for entries selected to show on screen
DATA: BEGIN OF /VPCOE/RDPVSRVGR_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /VPCOE/RDPVSRVGR.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /VPCOE/RDPVSRVGR_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /VPCOE/RDPVSRVGR_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /VPCOE/RDPVSRVGR.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /VPCOE/RDPVSRVGR_TOTAL.

*...processing: /VPCOE/RDPVSRVID................................*
TABLES: /VPCOE/RDPVSRVID, */VPCOE/RDPVSRVID. "view work areas
CONTROLS: TCTRL_/VPCOE/RDPVSRVID
TYPE TABLEVIEW USING SCREEN '0200'.
DATA: BEGIN OF STATUS_/VPCOE/RDPVSRVID. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/VPCOE/RDPVSRVID.
* Table for entries selected to show on screen
DATA: BEGIN OF /VPCOE/RDPVSRVID_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /VPCOE/RDPVSRVID.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /VPCOE/RDPVSRVID_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /VPCOE/RDPVSRVID_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /VPCOE/RDPVSRVID.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /VPCOE/RDPVSRVID_TOTAL.

*...processing: /VPCOE/RDP_GR_ID................................*
DATA:  BEGIN OF STATUS_/VPCOE/RDP_GR_ID              .   "state vector
         INCLUDE STRUCTURE VIMSTATUS.
DATA:  END OF STATUS_/VPCOE/RDP_GR_ID              .
CONTROLS: TCTRL_/VPCOE/RDP_GR_ID
            TYPE TABLEVIEW USING SCREEN '0400'.
*...processing: /VPCOE/VAPI_TYPE................................*
TABLES: /VPCOE/VAPI_TYPE, */VPCOE/VAPI_TYPE. "view work areas
CONTROLS: TCTRL_/VPCOE/VAPI_TYPE
TYPE TABLEVIEW USING SCREEN '0101'.
DATA: BEGIN OF STATUS_/VPCOE/VAPI_TYPE. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/VPCOE/VAPI_TYPE.
* Table for entries selected to show on screen
DATA: BEGIN OF /VPCOE/VAPI_TYPE_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /VPCOE/VAPI_TYPE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /VPCOE/VAPI_TYPE_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /VPCOE/VAPI_TYPE_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /VPCOE/VAPI_TYPE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /VPCOE/VAPI_TYPE_TOTAL.

*...processing: /VPCOE/V_CONFIG.................................*
TABLES: /VPCOE/V_CONFIG, */VPCOE/V_CONFIG. "view work areas
CONTROLS: TCTRL_/VPCOE/V_CONFIG
TYPE TABLEVIEW USING SCREEN '0500'.
DATA: BEGIN OF STATUS_/VPCOE/V_CONFIG. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/VPCOE/V_CONFIG.
* Table for entries selected to show on screen
DATA: BEGIN OF /VPCOE/V_CONFIG_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /VPCOE/V_CONFIG.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /VPCOE/V_CONFIG_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /VPCOE/V_CONFIG_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /VPCOE/V_CONFIG.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /VPCOE/V_CONFIG_TOTAL.

*...processing: /VPCOE/V_RCPNT..................................*
TABLES: /VPCOE/V_RCPNT, */VPCOE/V_RCPNT. "view work areas
CONTROLS: TCTRL_/VPCOE/V_RCPNT
TYPE TABLEVIEW USING SCREEN '0300'.
DATA: BEGIN OF STATUS_/VPCOE/V_RCPNT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/VPCOE/V_RCPNT.
* Table for entries selected to show on screen
DATA: BEGIN OF /VPCOE/V_RCPNT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /VPCOE/V_RCPNT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /VPCOE/V_RCPNT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /VPCOE/V_RCPNT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /VPCOE/V_RCPNT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /VPCOE/V_RCPNT_TOTAL.

*...processing: /VPCOE/V_TAXNUMT................................*
TABLES: /VPCOE/V_TAXNUMT, */VPCOE/V_TAXNUMT. "view work areas
CONTROLS: TCTRL_/VPCOE/V_TAXNUMT
TYPE TABLEVIEW USING SCREEN '0102'.
DATA: BEGIN OF STATUS_/VPCOE/V_TAXNUMT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/VPCOE/V_TAXNUMT.
* Table for entries selected to show on screen
DATA: BEGIN OF /VPCOE/V_TAXNUMT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /VPCOE/V_TAXNUMT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /VPCOE/V_TAXNUMT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /VPCOE/V_TAXNUMT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /VPCOE/V_TAXNUMT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /VPCOE/V_TAXNUMT_TOTAL.

*.........table declarations:.................................*
TABLES: */VPCOE/CONF_PARM              .
TABLES: */VPCOE/RDP_GR_ID              .
TABLES: /VPCOE/API_TYPE                .
TABLES: /VPCOE/CONFIG                  .
TABLES: /VPCOE/CONF_PARM               .
TABLES: /VPCOE/RDP_GR_ID               .
TABLES: /VPCOE/RDP_SMSRV               .
TABLES: /VPCOE/RDP_SRVGR               .
TABLES: /VPCOE/RDP_SRVID               .
TABLES: /VPCOE/RECIPIENT               .
TABLES: /VPCOE/TAXNUMTYP               .

* general table data declarations..............
  INCLUDE LSVIMTDT                                .
