*"* use this source file for any type of declarations (class
*"* definitions, interfaces or type declarations) you need for
*"* components in the private section
TYPES: GTY_T_UOM_ISO_CODE_T TYPE /VPCOE/TT_UOM_ISO_CODE_T.
TYPES: GTY_T_UOM_DIMENSION_T TYPE /VPCOE/TT_UOM_DIMENSION_T.
TYPES: GTY_T_UOM_T TYPE /VPCOE/TT_UOM_T.
TYPES: GTY_T_REGION_T TYPE /VPCOE/TT_REGION_T.
TYPES: GTY_T_PRODUCT_TYPE TYPE /VPCOE/TT_PRODUCT_TYPE_T.
TYPES: GTY_T_PRODUCT_GROUP TYPE /VPCOE/TT_PRODUCT_GROUP_T.
TYPES: GTY_T_MOVEMENT_TYPE TYPE /VPCOE/TT_MOVEMENT_TYPE_T.
TYPES: GTY_T_DD_TYPE TYPE /VPCOE/TT_DLVR_DOC_TYPE_T.
TYPES: GTY_T_DD_ITEM_CATEGORY_T TYPE /VPCOE/TT_DLVR_DOC_ITEM_TYPE_T.
TYPES: GTY_T_CURRENCY_T TYPE /VPCOE/TT_CURRENCY_T.
TYPES: GTY_T_COUNTRY_T TYPE /VPCOE/TT_COUNTRY_T.
